// Demo codes for testing without Supabase
const DEMO_CODES = {
  'WILD-FOUND-2024': 'T1',
  'WILD-ADV-2024':   'T2',
  'WILD-MAST-2024':  'T3',
}

// Production code prefixes (generated by scripts/generateCodes.js)
const VALID_PREFIXES = {
  'FOUND-': 'T1',
  'ADVAN-': 'T2',
  'MASTE-': 'T3',
}

export function validateCode(code) {
  if (!code || typeof code !== 'string') return null
  const upper = code.toUpperCase().trim()

  // Check demo codes first
  if (DEMO_CODES[upper]) return DEMO_CODES[upper]

  // Check production prefix pattern
  for (const [prefix, tier] of Object.entries(VALID_PREFIXES)) {
    if (upper.startsWith(prefix) && upper.length >= prefix.length + 4) {
      return tier
    }
  }
  return null
}

export function getTierFromCode(code) {
  return validateCode(code)
}
