export const SHADOW_PROMPTS = [
  "What recurring nightmare or unsettling dream image do you keep avoiding? What might it be trying to show you?",
  "In your dreams, who appears as a villain or threat? What aspect of yourself might they represent?",
  "What emotion do you refuse to feel while awake that surfaces in your dreams?",
  "Describe a dream where you felt powerless. Where in waking life do you feel the same?",
  "What dream character do you deeply dislike? What traits do they carry that you deny in yourself?",
  "Which dream scenario embarrasses you most to admit? What does the shame reveal?",
  "In dreams, what do you desire that feels forbidden or wrong? Where does that prohibition come from?",
  "What parts of yourself do you lock away in the dark? Do they appear in your dreamscape?",
  "Describe the last time a dream made you cry. What wound was being touched?",
  "Who in your dreams do you envy? What quality of theirs do you refuse to claim?",
  "What is the darkest impulse that has appeared in your dreams? Can you hold it without judgment?",
  "When your dream-self does something 'wrong', how do you feel upon waking? Is the guilt informative?",
  "What monster in your dreams would you most want to face and understand?",
  "Describe a dream where you were rejected or abandoned. How old did you feel inside that dream?",
  "What do you pretend not to want in waking life that your dreams give you freely?",
  "What aspect of the opposite gender appears in your dreams? How do you relate to that energy?",
  "Where in your dreamscapes do you feel safest? What does that safe place lack in your waking life?",
  "What would your shadow self say to you if it could speak directly?",
  "Name the three emotions your dreams most frequently generate. What do they have in common?",
  "What unfinished conversation appears repeatedly in your dream life? What remains unsaid?",
  "What do your childhood dreams and current dreams share? What thread connects them?",
  "In dreams, what roles do you always play? The rescuer, the victim, the observer? What does this show?",
  "What would change if you stopped fighting the dark images in your dreams and instead became curious?",
  "Describe a dream that felt like a punishment. What part of you issued that sentence?",
  "What beauty exists in your shadow? What gifts hide in what you have rejected?",
  "When you become lucid in a dream, what is the first impulse you suppress? Why?",
  "What do you fear most about truly knowing yourself? Does that fear appear in your dreams?",
  "Describe the dream version of your home. What rooms are locked? What do they contain?",
  "What would the wisest part of you say to the frightened part that generates your nightmares?",
  "In your dreams, who do you wish you could be that you would never admit to in daylight?",
  "What grief have you not allowed yourself to feel? Does it surface in your sleep?",
  "What dream has left you feeling the most alive? What does that aliveness point toward?",
  "Where in your dreams do you feel most free? What chains does that freedom remove?",
  "What dream figure do you most want to understand? Write them a letter.",
  "What would happen if you stopped running from the pursuer in your dreams and turned to face them?",
  "What part of your personality has been buried to make others comfortable?",
  "What desire feels too big, too strange, or too dangerous to voice aloud?",
  "In your dreams, what are you always searching for but never finding? What does the search itself mean?",
  "What dream has taught you the most about yourself? What lesson are you still resisting?",
  "What would you dream if you had absolute permission to dream anything at all?",
  "What emotion appears in your dreams that you have no name for in waking life?",
  "Describe a dream figure who offered you something. Did you accept? Why or why not?",
  "What recurring setting in your dreams carries the most emotional weight?",
  "In dreams, when do you feel most authentically yourself? What does that selfhood look like?",
  "What would integrating your shadow actually cost you? What familiar identity would dissolve?",
  "What lie do you tell yourself that your dreams seem to contest?",
  "What relationship pattern appears in dreams that mirrors an unresolved waking dynamic?",
  "What ancient or mythic figure appears in your dreamscape? What quality do they carry?",
  "If your shadow self had a mission statement, what would it be?",
  "What would full self-acceptance actually feel like? Can you glimpse it in any of your dreams?",
  "Describe the moment in a dream when you felt most powerful. Was that power frightening?",
  "What creative gift have you hidden away? Does it appear differently in your dreams?",
  "What would it mean to forgive yourself for the things that surface in your dream world?",
  "Which of your wounds is most active in your dreamscape right now?",
  "What gift is your unconscious trying to deliver through your most challenging dreams?",
  "Who in your dream world represents the version of you that got left behind?",
  "What does the darkness in your dreams want you to know?",
  "What would it look like to dream with compassion for all parts of yourself?",
  "What unspoken truth is your dream life whispering that your waking mind refuses to hear?",
  "What dream has stayed with you for years? What question does it still ask of you?",
  "What would wholeness feel like, if you stopped rejecting the parts your dreams keep presenting?",
]

export const SHADOW_PROMPTS_PSYCHOLOGICAL = [
  "What emotion do you find hardest to feel in front of others, and why?",
  "Which of your parent's traits do you most dislike seeing in yourself?",
  "What do you want that you're too ashamed to admit?",
  "When did you first learn it was unsafe to be fully yourself?",
  "What mask do you wear most consistently in daily life?",
  "What belief about yourself would change everything if it were false?",
  "Who in your life do you resent, and what does their freedom remind you of?",
  "What part of your childhood self have you abandoned?",
  "What are you defending yourself from in your closest relationships?",
  "What would you do differently if no one would ever find out?",
  "What do you judge most harshly in other people? Where does that live in you?",
  "What is your most chronic complaint about life? What are you refusing to change?",
  "When you imagine being truly seen by someone, what do you fear they'd find?",
  "What do you compulsively seek in others that you haven't given yourself?",
  "Which of your relationships reflects something unresolved in you?",
  "What are you still waiting for permission to do?",
  "What does your inner critic say most often? Where did it learn that?",
  "What are you lying to yourself about right now?",
  "If your anger could speak, what would it say it's protecting?",
  "What did you have to suppress to be loved as a child?",
  "What does success mean to you, and whose definition is that really?",
  "What part of yourself do you sacrifice to feel accepted?",
  "What would your 10-year-old self think of the life you're living?",
  "What are you addicted to that numbs a specific feeling?",
  "What story about yourself have you been telling so long it feels like fact?",
  "What boundary have you been refusing to set, and what does that cost you?",
  "Where in your life are you performing rather than being?",
  "What does loneliness reveal about what you haven't faced in yourself?",
  "When have you betrayed your own values, and what did you tell yourself to justify it?",
  "What are you secretly afraid makes you unlovable?",
  "What quality in others triggers envy in you, and what does that tell you?",
  "What have you never forgiven yourself for, and what would happen if you did?",
  "How do you punish yourself, and for what?",
  "What do you avoid because it would mean admitting something painful?",
  "Who are you when nobody is watching, and how is that different from who you perform?",
  "What do you say you want but consistently self-sabotage?",
  "What wounds are you still open about that you pretend are healed?",
  "What does your procrastination protect you from?",
  "Where in your life do you give your power away, and to whom?",
  "What feeling would you have to sit with if you stopped being busy?",
  "What narrative about your past is keeping you stuck?",
  "Where do you diminish yourself to make others comfortable?",
  "What kind of person do you secretly believe you don't deserve to be?",
  "What does your anxiety tell you it's trying to prevent?",
  "What did love look like in your family, and how has that shaped what you accept?",
  "What is the cost of your strongest habit?",
  "What would change in your life if you stopped seeking external validation?",
  "What have you let die inside yourself that still deserves to live?",
  "Where are you choosing comfort over growth, and what are you avoiding?",
  "If you had one year left, what would you stop pretending matters?",
]

export const SHADOW_PROMPTS_SPIRITUAL = [
  "What archetype are you living through right now — hero, exile, trickster, sage?",
  "What does the darkness in your dreams tell you about your waking self?",
  "If your soul chose this life with a purpose, what might that purpose be?",
  "What recurring symbol in your dreams has never been fully understood?",
  "Where in your waking life do you feel most like a stranger to yourself?",
  "What would it mean to fully surrender to what life is asking of you?",
  "What ancient wound are you carrying that did not begin with you?",
  "Which part of your psyche have you exiled to the unconscious, and what would it take to invite it back?",
  "What do you think you were meant to learn from your deepest loss?",
  "If your highest self could give you one instruction for the next year, what would it be?",
  "What does your relationship with death tell you about how you're living?",
  "What is sacred to you that you've been treating as ordinary?",
  "What would you create if you had no fear of judgment and unlimited time?",
  "Where are you resisting your own becoming?",
  "What does the void feel like to you, and what do you find when you sit in it?",
  "What part of you is the most ancient?",
  "If your life were a myth, what is the central trial you are being asked to pass?",
  "What is the gift hidden inside your greatest wound?",
  "Which relationships in your life are initiations in disguise?",
  "What does your shadow ask of you when it acts out?",
  "If consciousness itself had a message for you right now, what would it be?",
  "What is the dream you keep almost remembering?",
  "What is the quality of your inner silence when you stop filling it?",
  "What divine quality are you afraid to fully embody?",
  "If your body were an oracle, what is it currently saying?",
  "What are you being called to release that you have been clutching for years?",
  "What does the image of a perfectly still lake mean to you right now?",
  "Where does your ego end and your soul begin?",
  "What truth about yourself have you encountered in the liminal space between waking and dreaming?",
  "What does your highest wisdom know that your fear refuses to accept?",
  "What in your life is dying so that something new can be born?",
  "If the universe were conspiring in your favour, what would it be arranging right now?",
  "What is the medicine you carry that you have not yet offered the world?",
  "What is the difference between who you think you are and who you actually are?",
  "What would your soul say if it could speak directly to your mind?",
  "What is the myth you are unconsciously enacting in your life right now?",
  "Where does your sense of the sacred come from, and when do you feel it most?",
  "If you were a dream symbol, what would you represent?",
  "What part of your spiritual path are you avoiding because it would require real change?",
  "What is the lesson you have resisted the most, and what has resisting it cost you?",
  "What lives in the space between your breaths?",
  "If your dreaming mind is a teacher, what subject is it currently trying to teach you?",
  "What would it mean for you to be truly free — not free from something, but free as a state of being?",
  "What is the relationship between your suffering and your awakening?",
  "What ancestor's unfinished business might you be completing in this lifetime?",
  "If you stripped away everything you think you should be, what remains?",
  "What does the threshold state in WILD teach you about consciousness itself?",
  "What is the next version of you that is trying to emerge, and what is blocking it?",
  "What part of your inner landscape have you never visited with full presence?",
  "If love were the only real answer, what question does your life keep asking?",
]

export const INTEGRATION_PROMPTS = [
  "What is the single most important message from your last lucid dream?",
  "How does the lucidity you experienced in the dream world apply to your waking choices today?",
  "What did you create or change in the dream that you could mirror in waking life?",
  "What fear did you face in the lucid state? How does that translate to a real-world challenge?",
  "Describe the feeling of full lucid awareness. When do you access this clarity while awake?",
  "What did you learn about the nature of your own mind during the dream?",
  "What would you do differently in the dream if you revisited it? What does that tell you?",
  "What symbolic element from your last dream is asking to be integrated into your life?",
  "How did your dream-body feel different from your waking body? What does that difference reveal?",
  "What conversation did you have (or wish you had) in the lucid state? What needs to be said in life?",
  "What boundary did you set or need to set in the dream? Where in waking life does that apply?",
  "What gift, object, or insight did the dream give you? How will you honour it today?",
  "What did the dream show you about what you truly want, beneath all the social conditioning?",
  "What part of the dream experience do you most want to carry forward into your day?",
  "How has your understanding of consciousness shifted through this practice?",
  "What does the dream suggest about where your energy most wants to go right now?",
  "What healing happened in the dream space that you are ready to acknowledge?",
  "How did you interact with dream figures? What does that relationship mirror?",
  "What quality of awareness, creativity, or power is the dream inviting you to embody more fully?",
  "What would change in your waking life if you trusted your unconscious as much as you trust your rational mind?",
]

export const INCUBATION_THEMES = [
  { id: 'clarity', label: 'Mental Clarity', description: 'Seek insight and clear perception' },
  { id: 'healing', label: 'Physical Healing', description: 'Invite restorative and healing energy' },
  { id: 'creativity', label: 'Creative Breakthrough', description: 'Unlock hidden creative solutions' },
  { id: 'relationship', label: 'Relationship Wisdom', description: 'Understand a key relationship more deeply' },
  { id: 'purpose', label: 'Life Purpose', description: 'Connect with your deeper calling' },
  { id: 'fear', label: 'Face a Fear', description: 'Confront and transform a fear safely' },
  { id: 'past', label: 'Past Resolution', description: 'Revisit and resolve something from your past' },
  { id: 'future', label: 'Future Vision', description: 'Envision a positive future possibility' },
  { id: 'question', label: 'Answer a Question', description: 'Receive guidance on a specific question' },
  { id: 'spirit', label: 'Spiritual Connection', description: 'Deepen connection with spiritual dimensions' },
  { id: 'shadow', label: 'Shadow Integration', description: 'Meet and integrate a shadow aspect' },
  { id: 'ancestor', label: 'Ancestral Wisdom', description: 'Connect with ancestral knowledge' },
  { id: 'archetype', label: 'Meet an Archetype', description: 'Encounter a guiding archetypal figure' },
  { id: 'power', label: 'Personal Power', description: 'Reclaim lost power or strength' },
  { id: 'joy', label: 'Pure Joy', description: 'Experience unencumbered joy and freedom' },
  { id: 'grief', label: 'Grief Completion', description: 'Allow grief to move through and complete' },
  { id: 'body', label: 'Body Wisdom', description: 'Listen to what the body wants to communicate' },
  { id: 'nature', label: 'Nature Connection', description: 'Commune with natural forces and beings' },
  { id: 'skill', label: 'Skill Development', description: 'Practice and embody a skill in dream space' },
  { id: 'gift', label: 'Receive a Gift', description: 'Open to receiving an unexpected gift or message' },
]
